### ISSUE TITLE
Custom DataTypes Implementation

### ISSUE THREAD

**Issue by wlkrm** [umati/Dashboard-OPCUA-Client#117]
As a starting point see https://github.com/umati/Dashboard-OPCUA-Client/commit/0d4539c9574c745b6895d8eefa473d0bf5825175 @karstenroethig. 

TODO:

- [ ] The NamepsaceIndex of Machinery/Results should be dynamically read from the Server, currently its hardcoded to 8.
- [ ] (optional) Ideally, necessary information for decoding of custom data types schould be read from the server.

**Comment by wlkrm** [comment]
@karstenroethig, the NamespaceIndex is still hardcoded. This will cause problems when connecting to the datahub.

**Comment by karstenroethig** [comment]
Added dynamic read of Machinery/Results data types with 2291b25545d3c529c0b029ff348165881dd72ead
