### ISSUE TITLE
Integrate ModelChangeEvent Handling in Dashboard-OPC UA Client

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#201]

**Comment by GoetzGoerisch** [comment]
@mdornaus this was worked on here: https://github.com/umati/Dashboard-OPCUA-Client/tree/flatglas2

Please rebase and create PR.

CC: @Kantiran91

**Comment by mdornaus** [comment]
Pull Request #368

**Comment by DasbachVDMA** [comment]
Won't fix. Move to new gateway.
