### ISSUE TITLE
AnalogItemType is currently not correctly interpreted by client

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#205]
![Image](https://user-images.githubusercontent.com/47734341/178478788-a6606155-5995-4e2e-9bab-20ed8faaf513.png)

The properties are shown, but not the value.

**Comment by wlkrm** [comment]
See https://github.com/umati/PlasticsRubber/issues/14#issuecomment-1184186723

**Comment by wlkrm** [comment]
https://github.com/umati/Dashboard-OPCUA-Client/commit/1edb1e30c713aa0ba710a590a215ba43efd207f1
