### ISSUE TITLE
UInt64 Properties are not published

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#270]
The IMM PartsCounter is a Variable with a UInt64 datatype and not subscribed and published.

**Comment by Kantiran91** [comment]
@mdornaus Please check this also with the node sample server (see #212)

**Comment by mdornaus** [comment]
Can not reproduce this, all Uint64 Variables are Published with my local set Up:
![image](https://user-images.githubusercontent.com/91789872/223154306-80de2039-20a1-4f43-9f4f-188fa9feedde.png)
See Nominal Parts as example.
