### ISSUE TITLE
Make sure that Certificate is generated correctly

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#273]
Currently the ApplicationUri of the client and the generated certificate disagree.

Client
applicationUri = http://dashboard.umati.app/OPCUA_DataClient

Certificate
applicationUri  = urn:open62541.client.application

Thank you @erossignon  for reporting.

**Comment by ccvca** [comment]
The fix #275 should fix this. @erossignon the fix in included in ghcr.io/umati/dashboard-opcua-client:fix-connect
Could you please check if this fixes this bug, then we can merge this.

**Comment by erossignon** [comment]
ok, i'll do this

**Comment by ccvca** [comment]
#275 contains an update. Now the certificate and the session should use the same URI.
