### ISSUE TITLE
Fix handling of BadCertificateUriInvalid response on the CreateSession client side

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#274]
The client doesn't handle the BadCertificateUriInvalid well..

It goes in a infinite loop :
with "Client Connection Already Inititated..."

Thank you @erossignon for reporting.

**Comment by Kantiran91** [comment]
to be reproduced

**Comment by GoetzGoerisch** [comment]
Current workaround to disable / bypass URI validation.

**Comment by GoetzGoerisch** [comment]
I will investigate this further.

**Comment by DasbachVDMA** [comment]
Won't fix.
