### ISSUE TITLE
Integrate Client Version in Code

### ISSUE THREAD

**Issue by wlkrm** [umati/Dashboard-OPCUA-Client#355]
We need a way to identify which version of the client is running:

- Schema for version (Commit will not work because of rebasing etc.)
- Tag:Branch:Commit (https://stackoverflow.com/a/7261049)

**Comment by GoetzGoerisch** [comment]
https://github.com/open62541/open62541/blob/ffa4585e65b1c6e8988511de8abb756a897f2b9c/CMakeLists.txt#L57-L65
