### ISSUE TITLE
Publish Client Version via MQTT

### ISSUE THREAD

**Issue by wlkrm** [umati/Dashboard-OPCUA-Client#356]
will help with troubleshooting

https://github.com/umati/Dashboard-OPCUA-Client/issues/355

**Comment by Kantiran91** [comment]
@wlkrm @GoetzGoerisch Do you have an idea which topic we should use for this? Should this part of each message?

**Comment by GoetzGoerisch** [comment]
Currently we have `umati/opcUaToMqttOnline` for an online message.

Therefore my proposal `umati/gw-version`

@wlkrm any thoughts?

**Comment by GoetzGoerisch** [comment]
fixed with #387
