### ISSUE TITLE
[MT] Tool status not correct in JSON

### ISSUE THREAD

**Issue by GoetzGoerisch** [umati/Dashboard-OPCUA-Client#483]
**Describe the bug**
The tool locking state for MachineTools is currently not correct in the JSON structure.

**To Reproduce**

1. Run `development`version
2. Connect to opcua.umati.app:4840
3. Look for Tool Locking state in JSON

**Expected behavior**
```JSON
"Locked": {
            "properties": {
              "ReasonForLocking": 5
            },
            "value": false
          },
```

** Current behavior**

`"Locked": false,`

**Environment:**

- OS: alpine container
- OPC UA Dashboard Client Version `development
- Used Enviroment `umati.app` 
- OPC UA SDK of server `open62541`
.

**Additional context**

Works with RC3 of the Client

**Comment by mdornaus** [comment]
I think the problem is that the Locked type is not correctly detected as Variable Type. So it is published as an ObjectType would have been published. I dig deeper into it.
