### ISSUE TITLE
[Integration Test] Add Test for other  Companion Specification 

### ISSUE THREAD

**Issue by Kantiran91** [umati/Dashboard-OPCUA-Client#571]
Add mqtt_test for other  Companion Specification

- [ ] WoodWorking
- [ ] GMS
- [ ] FlatGlass
- [ ] Robotics

@GoetzGoerisch: Which  Companion Specification do need to be Tested and do have an opensource server?

**Comment by DasbachVDMA** [comment]
Won't do.
